android: PLATFORM=android -r features/Android/support -r features/Android -r features/step_definitions
ios: PLATFORM=ios APP_BUNDLE_PATH=apps/OSMaps-cal.app -r features/IOS/support -r features/IOS -r features/step_definitions
areport: --format progress --format html --out reports/report.html
orderTests: features/homescreen_navigation.feature features